config/routes.rb
Rails.application.routes.draw do
  root                'home#index'
  get 'about'     =>  'home#about'
  get 'contact'   =>  'home#contact'
  get 'faq'       =>  'home#faq'
  get 'policy'    =>  'home#policy'
#  post 'contact'  =>  'home#contact'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users do
    resources :groups
  end
  resources :groups do
    resources :users
  end
  resources :contributions
  resources :vote_challenges
  resources :vote_comments
  resources :comments
  resources :challenges
  resources :categories do
    resources :challenges
  end

match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/accept.rb
      class Accept < ActiveRecord::Base

  belongs_to :accepted, polymorphic: true
  belongs_to :acceptor, polymorphic: true

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :challenges
  
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

  belongs_to :creator, polymorphic: true

  has_many :accepts, as: :accepted
  has_many :user_acceptors, :through=> :accepts, :source => :acceptor, source_type: "User"
  has_many :group_acceptors, :through=> :accepts, :source => :acceptor, source_type: "Group"
  has_many :comments
  has_many :user_contributors, :through=> :contributions, :source => :contributor, source_type: "User"
  has_many :group_contributors, :through=> :contributions, :source => :contributor, source_type: "Group"
  has_many :contributions, as: :contributed
  has_many :vote_challenges

  has_and_belongs_to_many :categories

  validates :name,            presence: :true,
                              length: { maximum: 45 }
  validates :description,     presence: :true,
                              length: { within: 20..250 }

end

app/models/charge.rb
class Charge < ActiveRecord::Base

  has_many :users
  has_many :challenges

  validates_presence_of :amount
  validates_presence_of :challenge_id
  validates_presence_of :description
  validates_presence_of :user_id


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :challenge
  
  has_many :vote_comments

  validates :comment,           presence: true,
                                length: { within: 20..250 }

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base

  belongs_to :contributed, polymorphic: true
  belongs_to :contributor, polymorphic: true

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :accepts, as: :acceptor
  has_many :accepted, :through => :accepts, :source => :accepted, source_type: "Challenge"
  has_many :challenges, as: :creator
  has_many :contributed, :through => :contributions, :source => :contributed, source_type: "Challenge"
  has_many :contributions, as: :contributor
  has_many :users, through: :user_groups
  has_many :user_groups

  validates :name,            presence: :true,
                              length: { maximum: 45 }
  validates :description,     presence: :true,
                              length: { within: 20..250 }

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :accepts, as: :acceptor
  has_many :accepted, :through => :accepts, :source => :accepted, source_type: "Challenge"
  has_many :comments
  has_many :challenges, as: :creator
  has_many :contributed, :through => :contributions, :source => :contributed, source_type: "Challenge"
  has_many :contributions, as: :contributor
  has_many :groups, through: :user_groups
  has_many :user_groups
  has_many :vote_challenges
  has_many :vote_comments

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :group
  
end

app/models/vote_challenge.rb
class VoteChallenge < ActiveRecord::Base

  belongs_to :challenge
  belongs_to :user

end

app/models/vote_comment.rb
class VoteComment < ActiveRecord::Base

  belongs_to :user
  belongs_to :comment

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
    render layout: false
  end

  def faq
  end

  def policy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users/:id.:format
  def show
     authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vote_comments_helper.rb
module VoteCommentsHelper
end

app/views/home/about.html.erb
<% @page_title = "About Us" %>
<% @page_header = "About Us" %>

app/views/home/contact.html.erb
<% @page_title = "Contact" %>
<% @page_header = "Contact Us" %>

<div class="row">

  <div id="contact_message" class="col-sm-offset-2 col-sm-5">

    <form class="container form-horizontal" role="form">
    </form>

  </div>



  <div id="contact_info" class="col-sm-5">
  </div>

</div>

app/views/home/faq.html.erb
<% @page_header="FAQ" %>
<% @page_title="FAQ" %>

<h4>
  What do I do if the universe explodes?
</h4>

<p>
  Duck and Cover! ueinrgiun,euinvbiun iurtnunuh awsiudhyfg iqueybnrvnuri, vgfiu rnuienri oviurfgn eiru  iur ngfiueqrn iqeu ruqerio unqer viuer nviqeu rnviqeur nvnqueir ngvfiqeurn vique rnviquerbf vqieurbfvqeiru i qerug qer giuqner viq eurvhqierh vqeurin,voq ernvq eoruvnq eoriuvn, queionr vq ero.
</p>
<br />

<h4>
  What if I find a banana that is purple?
</h4>

<p>
  The universe has exploded. Please refer to FAQ for information about what to do in this situation. ueinrgiun,euinvbiun iurtnunuh awsiudhyfg iqueybnrvnuri, vgfiu rnuienri oviurfgn eiru  iur ngfiueqrn iqeu ruqerio unqer viuer nviqeu rnviqeur nvnqueir ngvfiqeurn vique rnviquerbf vqieurbfvqeiru i qerug qer giuqner viq eurvhqierh vqeurin,voq ernvq eoruvnq eoriuvn, queionr vq ero.
</p>
<br />

<h4>
  What do I do if one of the developers is chasing me?
</h4>

<p>
  Throw money at them and run. Developers are often distracted at the sight of money. ueinrgiun,euinvbiun iurtnunuh awsiudhyfg iqueybnrvnuri, vgfiu rnuienri oviurfgn eiru  iur ngfiueqrn iqeu ruqerio unqer viuer nviqeu rnviqeur nvnqueir ngvfiqeurn vique rnviquerbf vqieurbfvqeiru i qerug qer giuqner viq eurvhqierh vqeurin,voq ernvq eoruvnq eoriuvn, queionr vq ero.
</p>
<br />

<h4>
  What if I can not find the answer to one of my problems?
</h4>

<p>
  Don't ask a developer. They are often grumpy and require money and coffee to function. Go bother Greg Heileman. ueinrgiun,euinvbiun iurtnunuh awsiudhyfg iqueybnrvnuri, vgfiu rnuienri oviurfgn eiru  iur ngfiueqrn iqeu ruqerio unqer viuer nviqeu rnviqeur nvnqueir ngvfiqeurn vique rnviquerbf vqieurbfvqeiru i qerug qer giuqner viq eurvhqierh vqeurin,voq ernvq eoruvnq eoriuvn, queionr vq ero.
</p>
<br />

app/views/home/index.html.erb
 	 <div class="container-spacing2 text-center">
		 <h1 class="intro"> Welcome To Yak Yik!
		 </h1>


	 </div>
	 <div class="container-spacing1 bg-2 ">
	 	<h2 class="second"> Don't Miss the Race of the Century!
		</h2>

	</div>

	<div class="container-spacing2 bg-1">
		<h2 class="second"> Third!</h2>


	</div>

app/views/home/policy.html.erb
<% @page_header="Policy" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>