config/routes.rb
Rails.application.routes.draw do
  root                'home#index'
  get 'about'     =>  'home#about'
  get 'contact'   =>  'home#contact'
  get 'faq'       =>  'home#faq'
  get 'policy'    =>  'home#policy'
#  post 'contact'  =>  'home#contact'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users do
    resources :groups
  end
  resources :groups do
    resources :users
  end
  resources :contributions
  resources :vote_challenges
  resources :vote_comments
  resources :comments
  resources :challenges
  resources :categories do
    resources :challenges
  end

match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/vote_comment.rb
class VoteComment < ActiveRecord::Base

  belongs_to :user
  belongs_to :comment

end

app/controllers/vote_comments_controller.rb
class VoteCommentsController < ApplicationController
  before_action :set_vote_comment, only: [:show, :edit, :update, :destroy]

  # GET /vote_comments
  # GET /vote_comments.json
  def index
    @vote_comments = VoteComment.all
  end

  # GET /vote_comments/1
  # GET /vote_comments/1.json
  def show
  end

  # GET /vote_comments/new
  def new
    @vote_comment = VoteComment.new
  end

  # GET /vote_comments/1/edit
  def edit
  end

  # POST /vote_comments
  # POST /vote_comments.json
  def create
    @vote_comment = VoteComment.new(vote_comment_params)

    respond_to do |format|
      if @vote_comment.save
        format.html { redirect_to @vote_comment, notice: 'Vote comment was successfully created.' }
        format.json { render :show, status: :created, location: @vote_comment }
      else
        format.html { render :new }
        format.json { render json: @vote_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vote_comments/1
  # PATCH/PUT /vote_comments/1.json
  def update
    respond_to do |format|
      if @vote_comment.update(vote_comment_params)
        format.html { redirect_to @vote_comment, notice: 'Vote comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote_comment }
      else
        format.html { render :edit }
        format.json { render json: @vote_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_comments/1
  # DELETE /vote_comments/1.json
  def destroy
    @vote_comment.destroy
    respond_to do |format|
      format.html { redirect_to vote_comments_url, notice: 'Vote comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote_comment
      @vote_comment = VoteComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_comment_params
      params.require(:vote_comment).permit(:user_id, :comment_id)
    end
end

app/helpers/vote_comments_helper.rb
module VoteCommentsHelper
end

app/views/vote_comments/_form.html.erb
<%= form_for(@vote_comment) do |f| %>
  <% if @vote_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_comment.errors.count, "error") %> prohibited this vote_comment from being saved:</h2>

      <ul>
      <% @vote_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.number_field :comment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_comments/edit.html.erb
<h1>Editing Vote Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_comment %> |
<%= link_to 'Back', vote_comments_path %>

app/views/vote_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vote Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vote_comments.each do |vote_comment| %>
      <tr>
        <td><%= vote_comment.user_id %></td>
        <td><%= vote_comment.comment_id %></td>
        <td><%= link_to 'Show', vote_comment %></td>
        <td><%= link_to 'Edit', edit_vote_comment_path(vote_comment) %></td>
        <td><%= link_to 'Destroy', vote_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote comment', new_vote_comment_path %>

app/views/vote_comments/new.html.erb
<h1>New Vote Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', vote_comments_path %>

app/views/vote_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote_comment.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @vote_comment.comment_id %>
</p>

<%= link_to 'Edit', edit_vote_comment_path(@vote_comment) %> |
<%= link_to 'Back', vote_comments_path %>