config/routes.rb
Rails.application.routes.draw do
  root                'home#index'
  get 'about'     =>  'home#about'
  get 'contact'   =>  'home#contact'
  get 'faq'       =>  'home#faq'
  get 'policy'    =>  'home#policy'
#  post 'contact'  =>  'home#contact'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
 
  resources :users do
    resources :groups
  end
  resources :groups do
    resources :users
  end
  resources :contributions
  resources :vote_challenges
  resources :vote_comments
  resources :comments
  resources :challenges
  resources :categories do
    resources :challenges
  end

match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/accept.rb
      class Accept < ActiveRecord::Base

  belongs_to :accepted, polymorphic: true
  belongs_to :acceptor, polymorphic: true

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :challenges
  
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

  belongs_to :creator, polymorphic: true

  has_many :accepts, as: :accepted
  has_many :user_acceptors, :through=> :accepts, :source => :acceptor, source_type: "User"
  has_many :group_acceptors, :through=> :accepts, :source => :acceptor, source_type: "Group"
  has_many :comments
  has_many :user_contributors, :through=> :contributions, :source => :contributor, source_type: "User"
  has_many :group_contributors, :through=> :contributions, :source => :contributor, source_type: "Group"
  has_many :contributions, as: :contributed
  has_many :vote_challenges

  has_and_belongs_to_many :categories

  validates :name,            presence: :true,
                              length: { maximum: 45 }
  validates :description,     presence: :true,
                              length: { within: 20..250 }

end

app/models/charge.rb
class Charge < ActiveRecord::Base

  has_many :users
  has_many :challenges

  validates_presence_of :amount
  validates_presence_of :challenge_id
  validates_presence_of :description
  validates_presence_of :user_id


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :challenge
  
  has_many :vote_comments

  validates :comment,           presence: true,
                                length: { within: 20..250 }

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base

  belongs_to :contributed, polymorphic: true
  belongs_to :contributor, polymorphic: true

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :accepts, as: :acceptor
  has_many :accepted, :through => :accepts, :source => :accepted, source_type: "Challenge"
  has_many :challenges, as: :creator
  has_many :contributed, :through => :contributions, :source => :contributed, source_type: "Challenge"
  has_many :contributions, as: :contributor
  has_many :users, through: :user_groups
  has_many :user_groups

  validates :name,            presence: :true,
                              length: { maximum: 45 }
  validates :description,     presence: :true,
                              length: { within: 20..250 }

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :accepts, as: :acceptor
  has_many :accepted, :through => :accepts, :source => :accepted, source_type: "Challenge"
  has_many :comments
  has_many :challenges, as: :creator
  has_many :contributed, :through => :contributions, :source => :contributed, source_type: "Challenge"
  has_many :contributions, as: :contributor
  has_many :groups, through: :user_groups
  has_many :user_groups
  has_many :vote_challenges
  has_many :vote_comments

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  
  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :group
  
end

app/models/vote_challenge.rb
class VoteChallenge < ActiveRecord::Base

  belongs_to :challenge
  belongs_to :user

end

app/models/vote_comment.rb
class VoteComment < ActiveRecord::Base

  belongs_to :user
  belongs_to :comment

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
    render layout: false
  end

  def faq
  end

  def policy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
	

	<ul class="nav navbar-nav navbar-custom  list">
		<li><%= link_to "Contact Us",         	contact_path %></li>
		<li><%= link_to "About Us",     		about_path %></li>
		<li><%= link_to "Policy",        		policy_path %></li>
	</ul>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top" role="navigation">

  <div class="row">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "YakYik", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">

		  <% if user_signed_in? %>
  		  <li><%= link_to destroy_user_session_path, method: :delete do%><span class="glyphicon glyphicon-log-out"></span> Logout<% end %></li>
		  <% else%>
        <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-user"></span> Sign Up<% end %></li>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Login<% end %></li>
  		<% end %>
      </ul>
    </div>

    <div class="row">
      <div class="container-fluid collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav navbar-right list">



          <li><%= link_to "Stats",                    '#' %></li>
          <li><%= link_to "FAQ",                      faq_path %></li>
        </ul>

      </div>
    </div>
  </div>

</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? "Yakyik | #{@page_title} " : "Yakyik" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render '/layouts/shim' %>


</head>
<body>
	
  <div class="site-header">
    <%= render '/layouts/navbar' %>
    <%= render '/layouts/header' %>
    <div class="site-wrapper">
		
		 	
	  <%= yield %>
    </div>
 </div>

    <%= render '/layouts/footer' %>

</body>
</html>